# Generated by Django 3.1 on 2020-08-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='peopşe',
            new_name='people',
        ),
        migrations.AddField(
            model_name='meals',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, upload_to='meals/'),
        ),
    ]
