# Generated by Django 3.1 on 2020-09-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abaoutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name': 'Why Choose Us', 'verbose_name_plural': 'why choose us'},
        ),
    ]
