# Generated by Django 3.1 on 2020-09-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20200904_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abaoutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name': 'Why Choose Us', 'verbose_name_plural': 'Why Choose Us'},
        ),
    ]
